CREATE TABLE Persons(
	PersonID INT PRIMARY KEY IDENTITY(1,1)
	,FullName VARCHAR(255) NOT NULL
	,DateOfBirth Date NOT NULL
);

CREATE TABLE Roles(
	RoleID INT PRIMARY KEY IDENTITY(1,1)
	,[Role] VARCHAR(50) NOT NULL
);

CREATE TABLE PersonRole(
	PersonRoleID INT PRIMARY KEY IDENTITY(1,1)
	,PersonID INT NOT NULL
	,FOREIGN KEY (PersonID) REFERENCES Persons (PersonID)
	,RoleID INT NOT NULL
	,FOREIGN KEY (RoleID) REFERENCES Roles (RoleID)
);

CREATE TABLE Subjects(
	SubjectID INT PRIMARY KEY IDENTITY(1,1)
	,Title VARCHAR(255) NOT NULL
);

CREATE TABLE Teachers(
	TeacherID INT PRIMARY KEY IDENTITY(1,1)
	,PersonID INT NOT NULL
	,FOREIGN KEY (PersonID) REFERENCES Persons (PersonID)
	,SubjectID INT NOT NULL
	,FOREIGN KEY (SubjectID) REFERENCES Subjects (SubjectID)
);

CREATE TABLE Classes(
	ClassID INT PRIMARY KEY IDENTITY(1,1)
	,Title VARCHAR(10) NOT NULL
	,TeacherID INT NOT NULL
	,FOREIGN KEY (TeacherID) REFERENCES Teachers (TeacherID)
);

CREATE TABLE Pupils(
	PupilID INT PRIMARY KEY IDENTITY(1,1)
	,PersonID INT NOT NULL
	,FOREIGN KEY (PersonID) REFERENCES Persons (PersonID)
	,ClassID INT NOT NULL
	,FOREIGN KEY (ClassID) REFERENCES Classes (ClassID)
);

CREATE TABLE Grades(
	GradeID INT PRIMARY KEY IDENTITY(1,1)
	,SubjectID INT NOT NULL
	,FOREIGN KEY (SubjectID) REFERENCES Subjects (SubjectID)
	,PupilID INT NOT NULL
	,FOREIGN KEY (PupilID) REFERENCES Pupils (PupilID)
	,AnnualEstimate INT NOT NULL
);

CREATE TABLE Timetable(
	TimetableID INT PRIMARY KEY IDENTITY(1,1)
	,DateOfWeek VARCHAR(50) NOT NULL
	,LessonNumber INT NOT NULL
	,ClassID INT NOT NULL
	,FOREIGN KEY (ClassID) REFERENCES Classes (ClassID)
	,SubjectID INT NOT NULL
	,FOREIGN KEY (SubjectID) REFERENCES Subjects (SubjectID)
);